on:
  push:
    branches:
      - main

name: Render and Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Render Quarto site
        uses: quarto-dev/quarto-actions/render@v2
      
      - name: Commit and push rendered site
        run: |
          git config --local user.email "garoc371@gmail.com"
          git config --local user.name "GitHub Actions"
          git add docs/
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Auto-render site 🤖"
            git push
          fi